
import { Inter } from 'next/font/google'
import Provider from './provider'
import AppBar from '../components/AppBar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

    return (
        <html lang='en'>
            <body className={inter.className}>
                <Provider>
                    <AppBar />
                    <div className={"h-screen "}>{children}</div>
                </Provider>
            </body>
        </html>
    )
}

